INSERT INTO produits (categorie,img,titre,ref,prix,stock) VALUES ('Homme','src/m1.jpg','Masserati Successo Bleu','m1','179 $','20'); 
INSERT INTO produits (categorie,img,titre,ref,prix,stock) VALUES ('Homme','src/m2.jpg','Diesel Ms9 Champagne','m2','259 $','20'); 
INSERT INTO produits (categorie,img,titre,ref,prix,stock) VALUES ('Homme','src/m3.jpg','Boss Skymaster','m3','379 $','20'); 
INSERT INTO produits (categorie,img,titre,ref,prix,stock) VALUES ('Homme','src/m4.jpg','Diesel Mr Daddy Gris','m4','419 $','20'); 
INSERT INTO produits (categorie,img,titre,ref,prix,stock) VALUES ('Homme','src/m5.jpg','Lacoste Moon Noir','m5','199 $','20'); 
INSERT INTO produits (categorie,img,titre,ref,prix,stock) VALUES ('Homme','src/m6.jpg','Masserati Legend 2 Tons','m6','200 $','20'); 
INSERT INTO produits (categorie,img,titre,ref,prix,stock) VALUES ('Homme','src/m7.jpg','Boss Hero Bleu','m7','399 $','20'); 
INSERT INTO produits (categorie,img,titre,ref,prix,stock) VALUES ('Homme','src/m8.jpg','Lacoste Moon Argent','m8','199 $','20'); 
INSERT INTO produits (categorie,img,titre,ref,prix,stock) VALUES ('Homme','src/m9.jpg','Masserati Traguardo Noir','m9','269 $','20'); 
INSERT INTO produits (categorie,img,titre,ref,prix,stock) VALUES ('Femme','src/m10.jpg','Rosefield The Premium Bloss Noir','m10','89 $','20'); 
INSERT INTO produits (categorie,img,titre,ref,prix,stock) VALUES ('Femme','src/m11.jpg','Guess Cosmo Champagne','m11','189 $','20'); 
INSERT INTO produits (categorie,img,titre,ref,prix,stock) VALUES ('Femme','src/m12.jpg','Fossil Carlie Rose','m12','219 $','20'); 
INSERT INTO produits (categorie,img,titre,ref,prix,stock) VALUES ('Femme','src/m13.jpg','Fossil Fb- Blanc','m13','419 $','20'); 
INSERT INTO produits (categorie,img,titre,ref,prix,stock) VALUES ('Femme','src/m14.jpg','Rosefield The Premium Bloss Rose','m14','199 $','20'); 
INSERT INTO produits (categorie,img,titre,ref,prix,stock) VALUES ('Femme','src/m15.jpg','Casio Collection Vintage','m15','200 $','20'); 
INSERT INTO produits (categorie,img,titre,ref,prix,stock) VALUES ('Femme','src/m16.jpg','Casio Vintage Champagne','m16','70 $','20'); 
INSERT INTO produits (categorie,img,titre,ref,prix,stock) VALUES ('Femme','src/m17.jpg','Guess Bellini Argent','m17','149 $','20'); 
INSERT INTO produits (categorie,img,titre,ref,prix,stock) VALUES ('Femme','src/m18.jpg','Fossil Scarlette Mini Rose','m18','129 $','20'); 
INSERT INTO produits (categorie,img,titre,ref,prix,stock) VALUES ('Bracelet','src/m19.jpg','Bracelet Nouraya Argent Blanc','m19','45 $','20'); 
INSERT INTO produits (categorie,img,titre,ref,prix,stock) VALUES ('Bracelet','src/m20.jpg','Bracelet Noelle Argent','m20','39 $','20'); 
INSERT INTO produits (categorie,img,titre,ref,prix,stock) VALUES ('Bracelet','src/m21.jpg','Bracelet Gaspardine Maille Or','m21','89 $','20'); 
INSERT INTO produits (categorie,img,titre,ref,prix,stock) VALUES ('Bracelet','src/m22.jpg','Bracelet Hannen Argent','m22','419 $','20'); 
INSERT INTO produits (categorie,img,titre,ref,prix,stock) VALUES ('Bracelet','src/m23.jpg','Bracelet Nathali Argent','m23','35 $','20'); 
INSERT INTO produits (categorie,img,titre,ref,prix,stock) VALUES ('Bracelet','src/m24.jpg','Bracelet Ange Email Or','m24','119 $','20'); 
INSERT INTO produits (categorie,img,titre,ref,prix,stock) VALUES ('Bracelet','src/m25.jpg','Bracelet Aurida Papillon Or','m25','79 $','20'); 
INSERT INTO produits (categorie,img,titre,ref,prix,stock) VALUES ('Bracelet','src/m26.jpg','Bracelet Euphenia Maille','m26','149 $','20'); 
INSERT INTO produits (categorie,img,titre,ref,prix,stock) VALUES ('Bracelet','src/m27.jpg','Bracelet Gaspardine Maille','m27','109 $','20'); 
